#baseURL = "/implicit/user/andy/docsite/"
#baseURL = "/"
baseURL="/docsite"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "HDocumentation for minnoSuite"
theme = "learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
search = true
#uglyURLs = true
canonifyURLs = true
publishDir = "docs"

[params]
  editURL = "/"
  description = "Documentation for minnoSuite"
  author = "Andrew Dzikiewicz"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for minnoSuite"
weight = 1
languageName = "English"

